import Head from 'next/head'
import Link from 'next/link'
import MainLayout from '../../components/layouts/MainLayout'
// import { Navbar } from '../../components/Navbar'
// import Image from 'next/image'
// import styles from '../../styles/Home.module.css'

// si el fichero se llamara contact.jsx por la url habria que poner
// localhost:3000/contact/contact
// si se llama index.jsx entrará poniendo sólo localhost:3000/contact



export default function ContactPage() { // antes era home

  return (
    <MainLayout >
      <h1>Contact Page</h1>

      {/* className={ 'title' } */}
      <h1 className='title'> 
        Ir a <Link href="/">Home</Link>
      </h1>

{/* styles.description */}
      <p className={ 'description' }> 
        Get started by editing <code className={ 'code' }>
          pages/contact/index.jsx
        </code>
      </p>

    </MainLayout>
  )
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>about page</title>
  //       <meta name="description" content="Generated by create next app, contact..." />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <Navbar />

  //     <main className={styles.main}>

  //       <h1>Contact page</h1>

  //       <h1 className={styles.title}>
  //         Ir a <Link href="/"> home</Link>   
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/contact.jsx</code>
  //       </p>

        
  //     </main>


  //   </div>
  // )
}
