import Head from 'next/head'
import Link from 'next/link'
import { DarkLayout } from '../components/layouts/DarkLayout'
import MainLayout from '../components/layouts/MainLayout'
// import { Navbar } from '../components/Navbar'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function AboutPage() { // antes era home
  return (
    // <MainLayout>
    <>
      {/* <DarkLayout> */}

        <h1>About page</h1>

        <h1 className={'title'}>
          Ir a <Link href="/"> home</Link>
        </h1>

        <p className={'description'}>
          Get started by editing{' '}
          <code className='code'>pages/index.js</code>
        </p>

      {/* </DarkLayout> lo convierto a fragmento <>*/}

    {/* // </MainLayout> */}

    </>


    // <div className={'container'}>
    //   <Head>
    //     <title>about page</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <Navbar />

    //   <main className='main'>

    //     <h1>About page</h1>

    //     {/* <h1 className={styles.title}>
    //       Ir a <a href="/"> home</a>   
    //     </h1> */}
    //     {/* <a href="/about"></a> */}
    //     <h1 className={'title'}>
    //       Ir a <Link href="/"> home</Link>   
    //     </h1>

    //     <p className={'description'}>
    //       Get started by editing{' '}
    //       <code className='code'>pages/index.js</code>
    //     </p>


    //   </main>


    // </div>
  )
}

AboutPage.getLayout = function getLayout( page: JSX.Element ) {
    return(
      <MainLayout>
        <DarkLayout>
          { page }
        </DarkLayout>
      </MainLayout>
    )
  }