// import Head from 'next/head'
import Link from 'next/link'
import MainLayout from '../components/layouts/MainLayout'
// import { Navbar } from '../components/Navbar'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// el fichero podria llamarse index.jsx

export default function HomePage() { // antes era home
  /**return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App Francesc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { <nav>
        <a href="/">Home</a>
        <a href="/about">About</a>
        <a href="/contact">Contact</a>
      </nav> }
      <Navbar />

      <main className={styles.main}>

        

      </main>

    </div>
  )*/

  return(
    <MainLayout >
      <h1>Home Page</h1>

      {/* className={ 'title' } */}
      <h1 className='title'> 
        Ir a <Link href="/about">About</Link>
      </h1>

{/* styles.description */}
      <p className={ 'description' }> 
        Get started by editing <code className={ 'code' }>
          pages/index.js
        </code>
      </p>

    </MainLayout>
  )
}
